config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'rsvps#index'
    resources :rsvps, only: [:index, :destroy, :edit, :update]
  end

  root 'pages#home'
  
  resources :photos, only: [:index]
  resources :recommendations, only: [:index]
  
  # rsvps
  resources :rsvps, only: [:create, :update]
  get 'rsvp', to: 'rsvps#new', as: :new_rsvp
  get 'rsvp/guest', to: 'rsvps#guest'
  get 'rsvp/meal', to: 'rsvps#meal'
  get 'rsvp/message', to: 'rsvps#message'
  get 'rsvp/thanks', to: 'rsvps#thanks'
  get 'rsvp/sorry', to: 'rsvps#sorry'

  # pages
  get 'venue', to: 'pages#venue'
  get 'hotels', to: 'pages#hotels'

  # redirects
  get 'registry', to: redirect('https://www.amazon.com/registry/wedding/1XEYPJ43GL6AE')
  get 'uber', to: redirect(ENV['UBER_LINK'])
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :meal
  belongs_to :guest_meal, class_name: "Meal"

  def plus_one?
    !!Guest.search(name).try(:plus_one?) if name.present?
  end

  def first_name
    name.strip.split(' ').first if name.present?
  end

  def guest_first_name
    guest_name.strip.split(' ').first if guest_name.present?
  end

  def self.guest_count
    count = 0 

    Rsvp.where(attending: true).each do |rsvp|
      if rsvp.guest_name.present?
        count += 2
      else
        count += 1
      end
    end

    count
  end
end

app/controllers/admin/rsvps_controller.rb
class Admin::RsvpsController < Admin::AdminController
  before_action :find_rsvp, only: [:edit, :update, :destroy]

  def index
    @page_title = "RSVPs"
    @rsvps = Rsvp.all.order('id DESC').includes(:meal, :guest_meal)
    @meals = Meal.all.order(:short_name)
    @body_classes = "admin"
  end

  def edit
    @page_title = "Edit RSVP"
  end

  def update
    @rsvp.update(rsvp_params)

    if @rsvp.errors.any?
      render :edit
    else
      redirect_to admin_rsvps_path, notice: "RSVP ##{@rsvp.id} updated successfully."
    end
  end

  def destroy
    if @rsvp.destroy
      redirect_to admin_root_path, notice: "RSVP ##{@rsvp.id} has been deleted."
    else
      redirect_to admin_root_path, alert: "Failed to delete RSVP."
    end
  end

  private

    def find_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    def rsvp_params
      params.require(:rsvp).permit(:name, :attending, :guest_name, :meal_id, :guest_meal_id, :message)
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :setup_rsvp
  before_action :require_name, only: [:guest, :meal, :message, :thanks, :sorry]
  before_action :separate_combined_names, only: [:create]

  def new
  end

  def guest
  end

  def meal
  end

  def message
  end

  def thanks
  end

  def sorry
  end

  def create
    save_and_redirect
  end

  def update
    save_and_redirect
  end

  protected

  def setup_rsvp
    if params[:new].present?
      session[:rsvp_id] = nil
      redirect_to new_rsvp_path
    end
    
    @page_title = "RSVP"
    @rsvp = Rsvp.find_or_initialize_by(id: session[:rsvp_id])
  end

  def require_name
    redirect_to new_rsvp_path if @rsvp.name.blank?
  end

  def rsvp_params
    params.require(:rsvp).permit(:name, :email, :attending, :message, :guest_name, :meal_id, :guest_meal_id)
  end

  def previous_action
    @previous_action ||= begin
      actions = %w(new guest meal message thanks)

      if actions.include?(params[:previous_action])
        params[:previous_action]
      else
        actions.first
      end
    end
  end

  def separate_combined_names
    names = rsvp_params[:name].to_s.strip.split(/\s(and|&)\s/).map(&:strip).reject { |w| %w(and &).include?(w) }
    if names.length > 1
      params[:rsvp][:name] = names.first
      params[:rsvp][:guest_name] = names.slice(1)
    end
  end

  def save_and_redirect
    @rsvp.update(rsvp_params)

    if @rsvp.errors.any?
      render previous_action
    else
      session[:rsvp_id] = @rsvp.id

      if !@rsvp.attending?
        next_path = rsvp_sorry_path
      elsif previous_action == 'new' && (@rsvp.plus_one? || @rsvp.guest_name.present?)
        next_path = rsvp_guest_path
      elsif %w(new guest).include?(previous_action)
        next_path = rsvp_meal_path
      elsif previous_action == 'message' && rsvp_params[:message].present?
        next_path = rsvp_thanks_path
      else
        next_path = rsvp_message_path
      end

      redirect_to next_path
    end
  end
end

app/views/admin/rsvps/_modal.slim
.modal.fade id="message-#{rsvp.id}" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal"
          span &times;
        h4.modal-title Message from #{rsvp.name}
      .modal-body
        = simple_format(rsvp.message)
      / .modal-footer
      /   button.btn.btn-default data-dismiss="modal" Close

app/views/admin/rsvps/edit.slim
.page-header
  h2.page-title Edit RSVP

= render 'rsvps/errors'

= form_for @rsvp, class: "form", url: admin_rsvp_path(@rsvp) do |f|
  .form-group
    = f.label :name, "Name <small class='text-muted'>(required)</small>".html_safe, class: "input-label"
    = f.text_field :name, placeholder: "First & Last Name", class: "form-control", required: true, autofocus: true
  .form-group
    = f.label :attending, "Attending?", class: "input-label"
    = f.select :attending, [["Yes!", true], ["I can't make it...", false]], {}, { class: "form-control" }
  .form-group
    = f.label :name, "Guest Name", class: "input-label"
    = f.text_field :guest_name, class: "form-control"
  .form-group
    = f.label :meal_id, "Meal", class: "input-label"
    = f.select :meal_id, Meal.all.order(:name).collect { |m| [m.name, m.id] }, { include_blank: true }, { class: "form-control" }
  .form-group
    = f.label :guest_meal_id, "Guest Meal", class: "input-label"
    = f.select :guest_meal_id, Meal.all.order(:name).collect { |m| [m.name, m.id] }, { include_blank: true }, { class: "form-control" }
  .form-group.rsvp-message 
    = f.label :message, "Message", class: "input-label"
    = f.text_area :message, class: "form-control"
  .form-group
    = f.submit "Update", class: "btn btn-primary btn-block-xs"

app/views/admin/rsvps/index.slim
.page-header
  h2.page-title RSVPs

  button.btn.btn-default
    | Responses 
    span.badge = @rsvps.length
  = " "
  
  button.btn.btn-default
    | Guests  
    span.badge = Rsvp.guest_count
  = " "

  - @meals.each do |meal|
    button.btn.btn-default
      = "#{meal.short_name} "
      span.badge = meal.selection_count
    = " "

= render 'shared/flash'

- if @rsvps.present?
  table.table.table-striped.table-hover
    thead
      tr
        th Name
        th Attending?
        th Guest
        th Meal
        th Guest's Meal
        th Message
        th Received at
        th
    tbody
      - @rsvps.each do |rsvp|
        tr
          td = rsvp.name
          td
            - if rsvp.attending?
              b Yes
            - else
              i No
          td = rsvp.guest_name
          td = rsvp.meal.try(:name)
          td = rsvp.guest_meal.try(:name)
          td
            - if rsvp.message.present?
              button.btn.btn-default.btn-sm data-toggle="modal" data-target="#message-#{rsvp.id}" Show Message
              = render 'modal', rsvp: rsvp
          td = l(rsvp.created_at, format: :long)
          td
            = link_to "Edit", edit_admin_rsvp_path(rsvp), class: "btn btn-default btn-sm"
            | &nbsp;
            = link_to "Delete", admin_rsvp_path(rsvp), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure?" }

- else
  p
    i No responses yet!