config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'rsvps#index'
    resources :rsvps, only: [:index, :destroy, :edit, :update]
  end

  root 'pages#home'
  
  resources :photos, only: [:index]
  resources :recommendations, only: [:index]
  
  # rsvps
  resources :rsvps, only: [:create, :update]
  get 'rsvp', to: 'rsvps#new', as: :new_rsvp
  get 'rsvp/guest', to: 'rsvps#guest'
  get 'rsvp/meal', to: 'rsvps#meal'
  get 'rsvp/message', to: 'rsvps#message'
  get 'rsvp/thanks', to: 'rsvps#thanks'
  get 'rsvp/sorry', to: 'rsvps#sorry'

  # pages
  get 'venue', to: 'pages#venue'
  get 'hotels', to: 'pages#hotels'

  # redirects
  get 'registry', to: redirect('https://www.amazon.com/registry/wedding/1XEYPJ43GL6AE')
  get 'uber', to: redirect(ENV['UBER_LINK'])
end

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0"
    meta name="description" content=""
    title = [@page_title, "#mickleberry - 5/21/16"].compact.join(' | ')
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Rock+Salt', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag "/favicon.ico"
    = csrf_meta_tags
  body class="#{body_classes}" data-js-view="#{js_view}"
    nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed data-toggle="collapse" data-target=".navbar-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "#mickleberry", root_path, class: "navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li class="#{'active' if controller_name == 'pages' && action_name == 'venue'}"
              = link_to "Venue", venue_path
            li class="#{'active' if controller_name == 'photos'}"
              = link_to "Photos", photos_path
            li
              = link_to "Registry", "https://www.amazon.com/registry/wedding/1XEYPJ43GL6AE?tag=mickleberry-20"
            li class="#{'active' if controller_name == 'pages' && action_name == 'hotels'}"
              = link_to "Hotels", hotels_path
            li class="#{'active' if controller_name == 'recommendations'}"
              = link_to "Recomendations", recommendations_path
            li class="#{'active' if controller_name == 'rsvps'}"
              = link_to "RSVP", new_rsvp_path(new: true), class: "rsvp"

    .container-fluid
      #content
        = yield